// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rizhsrjmwocdbvkeyuke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpemhzcmptd29jZGJ2a2V5dWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODU1NjEsImV4cCI6MjA3MDU2MTU2MX0.F3oyP1pg5yrACIvtC1DozMVcdnsVdu6wrS50JvH8uRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});